export const LOGGED_IN_USER = 'LOGGED_IN_USER'

// semesters
export const GET_SEMESTERS = 'GET_SEMESTERS';

export const GET_SEMESTERS_BY_SLUG = 'GET_SEMESTERS_BY_SLUG';

export const DELETE_SEMESTER_BY_ID = 'DELETE_SEMESTER_BY_ID';

export const CLEAR_SEMESTER_ACTION = 'CLEAR_SEMESTER_ACTION'

// subjects
export const GET_SUBJECTS = 'GET_SUBJECTS'

export const GET_SUBJECTS_BY_SLUG = 'GET_SUBJECTS_BY_SLUG';

export const DELETE_SUBJECT_BY_ID = 'DELETE_SUBJECT_BY_ID';

// chapters
export const GET_CHAPTERS = 'GET_CHAPTERS'

export const GET_CHAPTER_BY_SLUG = 'GET_CHAPTER_BY_SLUG'

export const DELETE_CHAPTER_BY_ID = 'DELETE_CHAPTER_BY_ID'

// content
export const HANDLE_CE = 'HANDLE_CE'

export const HANDLE_CS = 'HANDLE_CS'

export const HANDLE_DC = 'HANDLE_DC'

export const HANDLE_CB = 'HANDLE_CB'

export const CONTENT_FORM_ERROR = 'CONTENT_FORM_ERROR'

export const UPDATE_FORM_ERRORS = 'UPDATE_FORM_ERRORS'

export const RESET_CONTENT_CREATE_FORM = 'RESET_CONTENT_CREATE_FORM'

export const GET_CONTENT_YEARS = 'GET_CONTENT_YEARS'

export const GET_CONTENTS = 'GET_CONTENTS'

export const GET_CONTENT_BY_SLUG = 'GET_CONTENT_BY_SLUG'

export const DELETE_CONTENT_BY_ID = 'DELETE_CONTENT_BY_ID'

// bloogs
// 1) categories
export const GET_BLOG_CATEGORIES = 'GET_BLOG_CATEGORIES'

export const GET_BLOG_CATEGORY_BY_SLUG = 'GET_BLOG_CATEGORY_BY_SLUG'

export const DELETE_BLOG_CATEGORY_BY_ID = 'DELETE_BLOG_CATEGORY_BY_ID'
